# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: maria-db
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: humanities@best-password.ByFar2025
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
